// src/components/Solid/ComponentForm.tsx
/** @jsxImportSource solid-js */
import { createEffect, createSignal } from "solid-js";
import { createStore } from "solid-js/store";

interface Props {
	component: "Solid" | "React" | "Svelte";
}
type formParams = {
	api_key: string | undefined;
	username: string | undefined;
	updateInterval: string | undefined;
	mode: "dev" | "prod";
};

const ComponentForm = (props: Props) => {
	const [formData, setFormData] = createSignal<FormData>();
	const [formDataObject, setFormDataObject] = createStore<formParams>({
		api_key: "",
		username: "",
		updateInterval: "",
		mode: "dev",
	});
	createEffect(() => {
		const keys: string[] = [];
		const lsFormString = localStorage.getItem("formData");
		const lsForm: formParams | null = lsFormString
			? JSON.parse(lsFormString)
			: null;
		const urlParams = new URLSearchParams(location.search);
		for (const key of urlParams.keys()) {
			keys.push(key);
		}
		if (lsForm) {
			setFormDataObject({
				api_key: lsForm.api_key,
				username: lsForm.username,
				updateInterval: lsForm.updateInterval,
				mode: lsForm.mode,
			});
		} else if (keys) {
			setFormDataObject({
				api_key: urlParams.get("api_key") as string | undefined,
				username: urlParams.get("username") as string | undefined,
				updateInterval: urlParams.get("updateInterval") as
					| string
					| undefined,
				mode: urlParams.get("mode") as "dev" | "prod" | undefined,
			});
		}
	});
	function submit(e: SubmitEvent) {
		e.preventDefault();
		setFormData(new FormData(e.target as HTMLFormElement));
		const params = new URLSearchParams(formData() as any);
		localStorage.setItem(
			"formData",
			JSON.stringify({
				api_key: formData()?.get("api_key"),
				username: formData()?.get("username"),
				updateInterval: formData()?.get("updateInterval"),
				mode: formData()?.get("mode"),
			})
		);
		window.history.replaceState({}, "", `${location.pathname}?${params}`);
		window.dispatchEvent(new Event("querychanged"));
	}
	const classes =
		props.component == "Solid"
			? "bg-[#2c4f7c] shadow-[#2c4f7c]"
			: props.component == "React"
				? "bg-[#61dafb] shadow-[#61dafb]"
				: props.component == "Svelte"
					? "bg-[#ff3e00] shadow-[#ff3e00]"
					: "";
	return (
		<form
			onsubmit={submit}
			method="post"
			class={` mx-auto my-20 flex max-w-max w-full flex-col items-center justify-center gap-4 text-nowrap rounded-md p-8 text-center font-bold ring-2 ring-black/50 shadow-lg ${classes}`}
		>
			<label class="flex w-full items-center justify-between gap-4 rounded-md bg-white/30 p-4 text-gray-900 transition-all duration-300 hover:ring-2 hover:ring-white/50 flex-col sm:!flex-row">
				API key:
				<span class="group relative z-10 size-8 cursor-help rounded-full">
					<svg
						xmlns="http://www.w3.org/2000/svg"
						x="0px"
						y="0px"
						width="100"
						height="100"
						viewBox="0 0 50 50"
						class="h-full w-full"
					>
						<path d="M 25 2 C 12.309295 2 2 12.309295 2 25 C 2 37.690705 12.309295 48 25 48 C 37.690705 48 48 37.690705 48 25 C 48 12.309295 37.690705 2 25 2 z M 25 4 C 36.609824 4 46 13.390176 46 25 C 46 36.609824 36.609824 46 25 46 C 13.390176 46 4 36.609824 4 25 C 4 13.390176 13.390176 4 25 4 z M 25 11 A 3 3 0 0 0 22 14 A 3 3 0 0 0 25 17 A 3 3 0 0 0 28 14 A 3 3 0 0 0 25 11 z M 21 21 L 21 23 L 22 23 L 23 23 L 23 36 L 22 36 L 21 36 L 21 38 L 22 38 L 23 38 L 27 38 L 28 38 L 29 38 L 29 36 L 28 36 L 27 36 L 27 21 L 26 21 L 22 21 L 21 21 z"></path>
					</svg>
					<span class="invisible absolute bottom-[200%] -translate-x-1/2 scale-75 text-nowrap rounded-lg bg-black p-4 text-2xl font-light text-white opacity-0 ring-2 ring-white transition-all duration-300 group-hover:visible group-hover:scale-100 group-hover:opacity-100">
						if you don't have an API key you can get one for free{" "}
						<a
							class="cursor-pointer font-bold underline"
							href="https://www.last.fm/api/account/create"
							target="_blank"
						>
							here
						</a>{" "}
					</span>
				</span>
				<input
					class="rounded-md border-none bg-gray-800 p-4 text-2xl text-gray-400 ring-2 ring-gray-900 focus:rounded-lg focus:ring-gray-700 overflow-ellipsis w-full"
					type="text"
					placeholder="last.fm public api key"
					name="api_key"
					value={formDataObject.api_key}
					required
				/>
			</label>
			<label class="flex w-full items-center justify-between gap-4 rounded-md bg-white/30 p-4 text-gray-900 transition-all duration-300 hover:ring-2 hover:ring-white/50 flex-col sm:!flex-row">
				Username:
				<input
					required
					class="rounded-md border-none bg-gray-800 p-4 text-2xl text-gray-400 ring-2 ring-gray-900 focus:rounded-lg focus:ring-gray-700 flex-1 w-full"
					type="text"
					placeholder="last.fm username"
					name="username"
					value={formDataObject.username}
				/>
			</label>
			<label class="flex w-full items-center justify-between gap-4 rounded-md bg-white/30 p-4 text-gray-900 transition-all duration-300 hover:ring-2 hover:ring-white/50 flex-col sm:!flex-row">
				Update Interval(ms):
				<input
					class="flex-1 rounded-md border-none bg-gray-800 p-4 text-2xl text-gray-400 ring-2 ring-gray-900 focus:rounded-lg focus:ring-gray-700"
					type="number"
					placeholder="10000"
					name="updateInterval"
					min="10000"
					max="99999"
					value={formDataObject.updateInterval}
				/>
			</label>
			<label class="flex w-full items-center justify-between gap-4 rounded-md bg-white/30 p-4 text-gray-900 transition-all duration-300 hover:ring-2 hover:ring-white/50 flex-col sm:!flex-row">
				Mode:
				<select
					class="flex-1 rounded-md border-none bg-gray-800 p-4 text-2xl text-gray-400 ring-2 ring-gray-900 focus:rounded-lg focus:ring-gray-700"
					name="mode"
					value={formDataObject.mode || "dev"}
				>
					<option value="dev">dev</option>
					<option value="prod">prod</option>
				</select>
			</label>
			<input
				type="submit"
				class="cursor-pointer rounded-md border-none bg-gray-800 p-4 px-8 text-2xl font-bold text-gray-400 outline-none ring-1 ring-gray-900 transition-all duration-300 hover:ring-2 hover:ring-black"
				value="Show"
			/>
		</form>
	);
};

export default ComponentForm;

// src/components/React/ComponentForm.tsx
/** @jsxImportSource react */

import type React from "react";

import { useEffect, useState } from "react";
import {
	Card,
	CardContent,
	CardDescription,
	CardFooter,
	CardHeader,
	CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import {
	Tooltip,
	TooltipContent,
	TooltipProvider,
	TooltipTrigger,
} from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";

type FormParams = {
	username: string | undefined;
	updateInterval: string | undefined;
	mode: "dev" | "prod" | undefined;
};

const themeConfig = {
	react: {
		accent: "bg-react/20",
		badgeClass: "text-react border-react/30 bg-react/10",
		liveIndicator: "bg-react fill-react",
		hoverAccent: "hover:text-react",
		borderAccent: "border-react/30",
		hoverBackground: "hover:bg-react/30 hover:text-react",
		button: "bg-react hover:bg-react/80",
	},
	svelte: {
		accent: "bg-svelte/20",
		badgeClass: "text-svelte border-svelte/30 bg-svelte/10",
		liveIndicator: "bg-svelte fill-svelte",
		hoverAccent: "hover:text-svelte",
		borderAccent: "border-svelte/30",
		hoverBackground: "hover:bg-svelte/30 hover:text-svelte",
		button: "bg-svelte hover:bg-svelte/80",
	},
	solid: {
		accent: "bg-solid/20",
		badgeClass: "text-solid border-solid/30 bg-solid/10",
		liveIndicator: "bg-solid fill-solid",
		hoverAccent: "hover:text-solid",
		borderAccent: "border-solid/30",
		hoverBackground: "hover:bg-solid/30 hover:text-solid",
		button: "bg-solid hover:bg-solid/80",
	},
	default: {
		accent: "#10b981",
		badgeClass: "bg-green-900/50 text-green-400",
		liveIndicator: "bg-green-500",
		hoverAccent: "hover:text-white",
		borderAccent: "border-gray-600",
		hoverBackground: "hover:bg-gray-700",
	},
};

function ComponentForm({ theme }: { theme: "react" | "svelte" | "solid" }) {
	const currentTheme = themeConfig[theme];

	const [formDataObject, setFormDataObject] = useState<FormParams>({
		username: "",
		updateInterval: "",
		mode: "dev",
	});

	const handleChange = (field: string, value: string) => {
		setFormDataObject((prev) => ({ ...prev, [field]: value }));
	};
	useEffect(() => {
		const keys: string[] = [];
		const lsFormString = localStorage.getItem("formData");
		const lsForm: FormParams | null = lsFormString
			? JSON.parse(lsFormString)
			: null;
		const urlParams = new URLSearchParams(location.search);
		for (const key of urlParams.keys()) {
			keys.push(key);
		}
		if (lsForm) {
			setFormDataObject({
				username: lsForm.username,
				updateInterval: lsForm.updateInterval,
				mode: lsForm.mode,
			});
		} else if (keys) {
			setFormDataObject({
				username: urlParams.get("username") as string | undefined,
				updateInterval: urlParams.get("updateInterval") as
					| string
					| undefined,
				mode: urlParams.get("mode") as "dev" | "prod" | undefined,
			});
		}
	}, []);
	function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
		e.preventDefault();
		const newFormData = new FormData(e.target as HTMLFormElement);
		const params = new URLSearchParams(newFormData as any);
		localStorage.setItem(
			"formData",
			JSON.stringify({
				username: newFormData?.get("username"),
				updateInterval: newFormData?.get("updateInterval"),
				mode: newFormData?.get("mode"),
			})
		);
		window.history.replaceState({}, "", `${location.pathname}?${params}`);
		window.dispatchEvent(new Event("querychanged"));
	}
	return (
		<div className="flex justify-center items-center">
			<Card
				className={cn(
					"w-full max-w-xl my-2 shadow-2xl border-gray-700 bg-gray-800/90 backdrop-blur-md",
					currentTheme.borderAccent,
					currentTheme.accent
				)}
			>
				<CardHeader className="pb-2">
					<CardTitle className="text-2xl font-bold text-white">
						Component Configuration
					</CardTitle>
					<CardDescription className="text-gray-300">
						Configure your Component settings and preferences
					</CardDescription>
				</CardHeader>
				<form onSubmit={handleSubmit}>
					<CardContent className="space-y-4">
						<div className="flex justify-between gap-4 flex-col sm:flex-row">
							<div className=" flex-1 space-y-2 relative">
								<Label
									htmlFor="username"
									className="text-sm font-medium text-gray-200"
								>
									Username
								</Label>
								<Input
									id="username"
									name="username"
									value={formDataObject.username}
									onChange={(e) =>
										handleChange("username", e.target.value)
									}
									className=" text-white placeholder:text-gray-400 focus:border-blue-500 focus:ring-blue-500"
								/>
							</div>
						</div>

						<div className="flex justify-between gap-4 flex-col sm:flex-row">
							<div className="sm:max-w-1/2 flex-1 space-y-2">
								<Label
									htmlFor="updateInterval"
									className="text-sm font-medium text-gray-200"
								>
									Update Interval (ms)
								</Label>
								<Input
									id="updateInterval"
									name="updateInterval"
									type="number"
									value={formDataObject.updateInterval}
									onChange={(e) =>
										handleChange(
											"updateInterval",
											e.target.value
										)
									}
									className=" text-white placeholder:text-gray-400 focus:border-blue-500 focus:ring-blue-500"
								/>
							</div>
							<div className="sm:max-w-1/2 flex-1 space-y-2">
								<Label
									htmlFor="mode"
									className="text-sm font-medium text-gray-200"
								>
									Mode
								</Label>
								<Select
									value={formDataObject.mode}
									name="mode"
									onValueChange={(value) =>
										handleChange("mode", value)
									}
								>
									<SelectTrigger
										id="mode"
										name="mode"
										className=" text-white focus:border-blue-500 focus:ring-blue-500 w-full"
									>
										<SelectValue placeholder="Select mode" />
									</SelectTrigger>
									<SelectContent className="bg-gray-700 border-gray-600">
										<SelectItem
											value="dev"
											className="text-white hover:bg-gray-600 focus:bg-gray-600"
										>
											Development
										</SelectItem>
										<SelectItem
											value="prod"
											className="text-white hover:bg-gray-600 focus:bg-gray-600"
										>
											Production
										</SelectItem>
									</SelectContent>
								</Select>
							</div>
						</div>
					</CardContent>
					<CardFooter className="flex justify-center pt-2">
						<Button
							type="submit"
							className={cn(
								"w-full sm:w-auto bg-blue-600 hover:bg-blue-700 text-white",
								currentTheme.button
							)}
						>
							Save & Render
						</Button>
					</CardFooter>
				</form>
			</Card>
		</div>
	);
}

export default ComponentForm;
